services:
  web:
    build: .
    container_name: foolslide_web
    ports:
      - "8080:80"
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./content/themes:/var/www/html/content/themes
      - ./application:/var/www/html/application
      - content_comics:/var/www/html/content/comics
      - content_tags:/var/www/html/content/tags
      - content_cache:/var/www/html/content/cache
  db:
    image: mysql:5.6
    container_name: foolslide_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: foobar
      MYSQL_DATABASE: foolslide_db
      MYSQL_USER: foolslide_user
      MYSQL_PASSWORD: foobar
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33061:3306"

volumes:
  db_data:
  content_comics:
  content_tags:
  content_cache:
